filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
releases:
- chart: jxgh/local-external-secrets
  version: 0.0.14
  name: local-external-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
